### ISSUE TITLE
Vaadin Charts license issue

### ISSUE THREAD

**Issue by Cantek** [johannest/loadtestdriver#1]
Setting up the Jar file under lib and adding the dependencies part goes well until recompiling the widgetsets.
Widgetsets can not be compiled and tomcat server can not run because of that. This happens because of the additional dependency being added for vaadin charts. Since vaadin charts is under license protection without a valid vaadin charts license it can not be used. Deleting it does not solve the issue because it is being added automatically after every IVY resolve. We have only testbench license which is not sufficient enough in that case. Hope to see this plug-in running soon. Load Testing is a big issue with Vaadin Applications. 

I am using Eclipse Mars V2 with JRE 1.7 on TomcatServer 7. Vaadin version : 7.6.6, Testbench 4.2. Project is a Vaadin Web Application project using IVY.

**Comment by johannest** [comment]
This should be fixed in just released version 0.0.2.
