### ISSUE TITLE
PhantomJS issue even after version 2.1.1 is installed 

### ISSUE THREAD

**Issue by Cantek** [johannest/loadtestdriver#2]
After version 2 charts issue is disappeared. I also realized that the jar file is not being properly run under JRE 1.7. But 1.8 is OK. After figuring this out, I got the error related to PhantomJS. PhantomJS is installed and defined in PATH variables. Version is 2.1.1 . But even tough  I keep getting following ERROR ::

The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html . 

I tried finding the part which PhantomJS is used and defined with the PATH of the binary file inside the source code of the project but I am empty handed. 

I have no clue what is the issue here. Maybe a step missed on the sample usage? Maybe something related to Gatling? Maybe a configuration line in somewhere? I have no idea.

**Comment by johannest** [comment]
Which operating system you used when you tested the add-on?

**Comment by Cantek** [comment]
Windows 10 is used on my Computer. Inside the PATH variable I put the path for Phantomjs executable. And on my command line in any folder Phantomjs is accessible.

**Comment by johannest** [comment]
Ok, thanks for the info. I'll try this with modern.ie Win10 asap. (Using Mac myself)

**Comment by johannest** [comment]
This should work, tested with clean Win10 installation. Check following things:
1. You have path to the folder containing phantomjs.exe in you Windows' Environment variables -> System variables -> Path
2. If you set the Path above, remember to open new command prompt after that if you start test from command line (or restart Eclipse)
3. You have write access to paths you set in the Testbench test case's LoadTestDriver setup
4. You have testbench license file in you User directory
5. Make sure you have allowed phantomjs to access the network (Windows' firewall should ask permission in first run)

**Comment by johannest** [comment]
I'll close the issue, please reopen if you can't get this working with above instructions

**Comment by Cantek** [comment]
OK, this is promising. Now we have passed that step and came to an other issue telling me Connection refused: no further information: /192.168.46.2:8080. But all the earlier steps are running smoothly now. Gatling log screen loads but nothing is written or logged on that permanent screen just the tag administration is there. There is an other Gatling screen which loads too but being closed nearly immediately without letting me see what is on it.

**Comment by johannest** [comment]
1. Which application server you are using, and does it's configuration allow all ip addresses? Does that IP above work in your browser? For example, in case of Wildfly one must allow other that localhost with -b 0.0.0.0 command line parameter.

2. Do you have several network adapters with different IP addresses? Can you try to configure the test with explicitly specifying another ip address with .withIpAddress("your.another.ip.add").

3. Can you also verify that your firewall is not blocking this?

**Comment by Cantek** [comment]
1 - I am trying it on my local server which is localhost - 127.0.0.1 with Tomcat 8 .
2 - Nope I have only one. 
3 - My Firewall is off.

My server is not serving on this IP address -> 192.168.46.2:8080 but the driver is being initiated with local ip address which is 192.168.46.2 and I am giving it the port number as follows : 

getDriver().get(LoadTestDriver.getLocalIpAddressWithPortAndContextPath(8080,"EFaturaFaktoring/"));

I think this is why it can not access to the server. My server runs on localhost:8080 . I checked the usable functions of LoadTestDriver and it always uses local ip address. So I need to make my server to be accessable on my local ip address in this case?

**Comment by johannest** [comment]
Yes, you have to allow an access to your server with ip-address. That limitation originates from PhantomJS which proxy unfortunately wont work with 'localhost' nor '127.0.0.1'. Which app server you use? It should be straightforward to allow ip-address access to most application servers (see above for Wildfly's command line parameter).

**Comment by johannest** [comment]
https://github.com/ariya/phantomjs/issues/11342

**Comment by johannest** [comment]
I'll update my "documentation" on this. Please, tell does this work for you after configuring your application server like discussed above.

**Comment by Cantek** [comment]
I think I made it work but How I can see the results?

**Comment by johannest** [comment]
Do you mean the results of running the test against you server? At the moment LoadTestDriver doesn't directly run the test, but you can easily run it with Gatling or you can include it into your webapp's unit tests (see this example project for how to do it: https://github.com/johannest/testbench-demo/tree/master/webinar-ui/src/test)

**Comment by johannest** [comment]
I can add a possibility to run the test directly after recording too, if you wish to have that kind of feature. I'll at least make an "issue" for it

**Comment by Cantek** [comment]
I am using it from inside a Vaadin project with TestBench script. So I dont thin an external runner is needed. But The issue is I can not see a report that I can view what has been done in how many seconds with how many threads and so on. I think Gatling is able to provide such reports and your plugin is already using it so I guess there should be a report in somewhere. But I can not really find anything like that.

**Comment by johannest** [comment]
At the moment you will need external Gatling or gatling-maven-plugin to run a test. If you use gatling-maven-plugin to run the test, then results are stored into your projects target/gatling folder

**Comment by Cantek** [comment]
No, I am using direct JUnit run for that on Eclipse as it is described for testBench test scripts. 
So, in this case, if I want to see a report I need to run tests from Gatling? I have to setup gatling to work with my project?
